### ISSUE TITLE
upgrade to django 1.4

### ISSUE THREAD

**Issue by colemickens** [CoJMC/jaam#30]
Investigate upgrading to django-1.4.

There is at least one feature we'd benefit from, though I'm not sure if I'll have time to dig it back out and finish it.

Potential issues:
- migrations (lulz)
- admin fields/buttons have new prefixes, may break custom JS in the admin (pretty sure this will be an issue)
- other fun things?

Would need to have a good run through of user testing, I'd recommend clearing the database. It'd be cool to give this a few run-throughs on the Monday after spring break and see if we want to try to spring 1.4 on them and have them test with it or not. We'll see how far I get with it.

**Comment by ngraef** [comment]
This would be nice.

**Comment by colemickens** [comment]
So I'm currently being roadblocked by Haystack. Turns out Haystack is working on version 2 and it is required for Django-1.4. Version 2 is currently in beta. Thoughts? I'm thinking of throwing version 2beta in the requirements.txt, running it and seeing if it blows up.

My fear is that the Haystack API has changed between 1.2.6 and 2.0.

**Comment by ngraef** [comment]
I say do it. We're not really using search right now anyway, and it's not a requirement from CoJMC. @DDropinski can check what he implemented and update if necessary.

**Comment by colemickens** [comment]
I think I got it working anyhow. I had to move search_indexes.py to inside jounrnalism/ so that haystack would discover it. (I think you had it in the "appropriate" place David, but I can't for the life of me figure out how to manually register the SearchIndex'es in that file manually with the default Haystack Site since they sort of clobbered that level of configuration in the move to Haystack 2.0. You can check the latest docs on RtD and check out the transition document to see what I meant.

I _think_ it should be working again... I'll leave it as an exercise for Monday to figure out how much I've broken, but I think between this and the pub/unpub'd stuff, I've had a positive contribution over the last couple days.

Not that I'm happy at all with TastyPie right now, it decided to make me do some copy-paste stuff because of how they use nested classes and how inheritance works in Python. Oh well, it's pretty obvious what's going on in there.

**Comment by colemickens** [comment]
Anyway, this should be "finished" as soon as I get it committed. It does need to be tested, especially to make sure I've not royally screwed up Haystack.
