### ISSUE TITLE
Privacy Policy / Terms of Service

### ISSUE THREAD

**Issue by colemickens** [CoJMC/jaam#36]
We need to get a boilerplate Privacy Policy and/or Terms of Service that we can link to.

**Comment by dsbramhall** [comment]
What exactly is involved with this? Is this something we'll need to get
from Adam/Matt/Gary/Journalism peoples?

On Sat, Mar 24, 2012 at 6:01 PM, Cole Mickens <
reply@reply.github.com

> wrote:
> 
> We need to get a boilerplate Privacy Policy and/or Terms of Service that
> we can link to.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/CoJMC/jaam/issues/36

## 

David S. Bramhall
Jeffrey S. Raikes School of Computer Science and Management
Design Studio Product Manager
Electrical Engineering - Masters 2012
University of Nebraska - Lincoln
dsbramhall@gmail.com
Mobile: 402-312-1664

**Comment by colemickens** [comment]
Yeah, it was just something I thought of this morning.

**Comment by dsbramhall** [comment]
Alright. I'll repeatedly ask them about it. Kind of like shooting multiple
arrows at them until one finally hits. We discussed it with them earlier
on, but hasn't been discussed in a while.

On Mon, Mar 26, 2012 at 12:26 AM, Cole Mickens <
reply@reply.github.com

> wrote:
> 
> Yeah, it was just something I thought of this morning.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/CoJMC/jaam/issues/36#issuecomment-4688100

## 

David S. Bramhall
Jeffrey S. Raikes School of Computer Science and Management
Design Studio Product Manager
Electrical Engineering - Masters 2012
University of Nebraska - Lincoln
dsbramhall@gmail.com
Mobile: 402-312-1664
