### ISSUE TITLE
Make the FB/Twitter Share Inline

### ISSUE THREAD

**Issue by colemickens** [CoJMC/jaam#50]

**Comment by colemickens** [comment]
Just means finishing up the share widgets as we discussed in the meeting. I think this is nearly done, yes? Minus fixing the facebook app id.

**Comment by DDropinski** [comment]
Did we ever decide the particular style we want to go for? Do we want to keep their style or swap it out? I can't remember right now.

**Comment by colemickens** [comment]
Basically we're going with what you and I had been discussing. [Share] pops up a window with the appropriate share widgets inside.

**Comment by DDropinski** [comment]
Okay, sounds good. Then, yes, it's basically done. It depends if we would want to change how they styled the Share button.

**Comment by colemickens** [comment]
Ah, yeah. I think they want it up by the login/logout/my profile/notification/search.
