### ISSUE TITLE
Admin can't assign journalist as content creator

### ISSUE THREAD

**Issue by ngraef** [CoJMC/jaam#58]
The "admin" section (published, journalist) is missing.

**Comment by ngraef** [comment]
This is only on the deploy....

**Comment by ngraef** [comment]
For only some content types... (i.e. photos)

**Comment by mattclaycomb** [comment]
redeploying fixed it

**Comment by ngraef** [comment]
This is broken again after @colemickens deploy... what's up?

**Comment by colemickens** [comment]
GR. Specifically after I deployed? Not that that really makes any sense. I might have to bug the gondor guys today or something. We don't even do any kind of logic to determine whether or not to show that field do we? Or do we check to make sure it's being initially created? Based on Adam/whoever's note today in the Facebook group, we may be able to eliminate that logic altogether. :S

**Comment by ngraef** [comment]
So..... I just realized you didn't deploy your fix for a different issue. The last/current deploy is the one that "fixed" this issue.

**Comment by ngraef** [comment]
finally fixed.
