### ISSUE TITLE
Get Profile Picture from Facebook/Twitter?

### ISSUE THREAD

**Issue by colemickens** [CoJMC/jaam#66]
Maybe? Feature fo sho.

**Comment by calliehelms** [comment]
If you give me 5 minutes of your time, Cole, I can probably figure this one out.

https://graph.facebook.com/1500930644/picture (your profile picture)

**Comment by colemickens** [comment]
I see your picture :P. Whatcha need me for?

**Comment by calliehelms** [comment]
I am a bit confused on the Facebook oauth file. like, should I add code in def get_user_details(self, response):?

**Comment by colemickens** [comment]
Which file are you referring to?

**Comment by calliehelms** [comment]
Apparently a file called Facebook.py that's in my build :p. Didn't realize that-- I just searched for where we pull the facebook data. my question is, where is the code that syncs the facebook data with the user's profile?

**Comment by colemickens** [comment]
;) I would definitely not recommend  editing anything in your src/ or build/ directories; might work for you but no one else. I think the rest of that code is in journalism/models.py. Look at lines 85 and 91. I think those both handle stuff from socialauth.

This page talks about how to "listen" for the signal that comes back from the social auth. https://github.com/omab/django-social-auth

**Comment by calliehelms** [comment]
So, in theory it works, except that the returned image is too small. The maximum width we can return is 200 px. (The page looks best with 330 px wide photos. We can rework this is needed).
