### ISSUE TITLE
User Profile Link (by log-out) Can become broken

### ISSUE THREAD

**Issue by calliehelms** [CoJMC/jaam#83]
Click on a user's profile that is not your own-- it will change the User Profile to the last profile you viewed.

Example: You are logged in as user "Sara Something." Your personal URL is jaam.us.to/sara

You have a friend whose user is "Claire Something." Her personal URL is jaam.us.to/claire

Once you visit Claire's page, the "User Profile" in the top bar will read "Claire Something."

This is not your profile.

Not a big deal if this doesn't get fixed, I don't think.

**Comment by DDropinski** [comment]
Alright, I think this is fixed. It was also happening in photos, but it should be completely fixed now.
